---
title: "About this site and course"
---

This is the GitHub website for the course **Practical Computing Skills for Biologists**
(a section of PLNTPTH8300 -- Current Topics in Plant Pathology),
a 2-credit online-only course at Ohio State University during the Spring
semester of 2021.
The course is taught by [Jelmer Poelstra](mailto:poelstra.1@osu.edu)
from the [MCIC](https://mcic.osu.edu).

### Course description

As datasets have rapidly grown larger in biology,
coding has been recognized as an increasingly important skill for biologists.
Yet in fact, basic coding skills and "computational thinking" are highly beneficial
for any scientist, paving the way for more efficient and reproducible research.

In this course, students will gain hands-on experience with a set of general and
versatile tools for day-to-day work with data sets small and large alike.
The course's focus is on foundational skills such as working in the Unix shell,
coding in Python, organizing, documenting, version-controlling and sharing research, 
submitting jobs to a compute cluster, and building flexible workflows.
Taken together, this will allow students to reproduce their own work,
and have others reproduce their work, with as little as a single command.

### More information

For additional general information about the course,
see the page [Practical course information](../../overview_course.html).

#### Overview of topics

- [Shell tools](overviews_shell.html) and [Shell scripting](overviews_shellscript.html) (4 modules)
- [Coding in Python](overviews_python.html) (5 modules)
- [Computing at OSC with SLURM and Conda](posts/week-06/) (1 module)
- [Version control with Git and GitHub](posts/week-03/) (1 module, applied throughout)
- [Project documentation with Markdown and project organization](posts/week-02) (1 module, applied throughout)
- [Reproducible workflows with Snakemake](posts/week-13) (1 module)

#### Course books

- **_Primary_**:
  Allesina S, Wilmes M (2019).
  *[Computing Skills for Biologists](https://library.ohio-state.edu/record=b8624007~S7)*.
  Princeton UP.
  
- **_Secondary_**:
  Buffalo V (2015).
  *[Bioinformatics Data Skills: Reproducible and Robust Research with Open Source Tools](https://library.ohio-state.edu/record=b8538907~S7)*.
  O'Reilly Media, Inc.

### CarmenCanvas website

If you are a student in this course, you should also refer to the
[CarmenCanvas site for this course](https://osu.instructure.com/courses/92221).[^1]

[^1]: You can always find the link to the CarmenCanvas site in the top-right
     corner of this site by clicking on the graduation cap icon.

