---
title: "Final project: Progress report"
output:
  distill::distill_article:
    self_contained: false
---

<br>

### Please report on your progress for your final project (due Tuesday, Apr 13). <span style="color:coral"><i>[10 points]</i></span>

<br>

I would like to see the following in your final project repository:

1. **One or more (Bash/Python/R) scripts with a significant amount code.**
   <span style="color:coral"><i>[4]</i></span>
   
   The scripts do not yet need to be complete or functioning,
   but make sure I can understand what you are trying to do.
   Also, it should be clear what the general purpose of the scripts is.
   
   You can earn as many points with clarity of purpose and documentation
   (use comments!) as with the code itself. 
   
2. **An overview of all the scripts you envision writing, and their functions.**
   <span style="color:coral"><i>[3]</i></span>
   
   This is essentially a more worked-out version of the technical description
   you wrote in your proposal (some remaining uncertainties are fine!).
   
   Having learned about Snakemake, you should include how you
   want to implement being able to (re)run the entire pipeline/workflow:
   with Snakemake, or a Bash or Python script.
   
3. **A to-do list**. <span style="color:coral"><i>[1.5]</i></span>
   
   This could be a separate list or it could be (partially)
   integrated with the overview of scripts mentioned above.

Both the technical description and the to-do list would be suitable for the
main `README.md` of the project
(and it would be good to continue to update these later on).
But you could also create separate documents for each,
whatever works better for you.
  
### Some general pointers:

- I will also start looking at your **Git commits and associated commit messages**.
  <span style="color:coral"><i>[1.5]</i></span>
  
  I will not grade this harshly, and will just skim you commit history,
  but *will* subtract points if:
  
  - Your commits do not form logical units at all --
    especially if they include work on multiple unrelated items.
    ("Oversplitting" of commits, i.e. having some really small commits that
    are not as much of a problem, that just tends to happen unless you amend
    commits.)
  
  - Your commit messages are consistently uninformative
    ("*Update file X*" is generally not enough -- especially when repeated).

- You can also flag specific things **that you would like feedback/advice on**,
  perhaps best in the GitHub Issue mentioned below.

- Once again, **tag me (`@jelmerp`) in an "Issue" on GitHub** and make sure you
  point me to the places you want me to look,
  particularly if you have a lot going on
  (in such cases, I won't grade files that you don't point me to).

- *Some of you already had most of these pieces in place in your
  repository when I looked at your proposal.
  If that is the case, just point me where to look -- you don't necessarily
  need to restructure things for this checkpoint.*
  
Remember that I have added some topic overviews to the GitHub
site that should be helpful as you work on you final project --
see the top navigation bar.
