---
title: "Final project: proposal"
output:
  distill::distill_article:
    self_contained: false
---

**Write a concise, informal summary of what you plan to do for your final project (due Tuesday, Mar 23). <span style="color:coral"><i>[10 points]</i></span>**

<div class="content-box-info">

-   *For general information about devising a project and expectations for your project, please see [this page](final_project.html).*
-   If you want to primarily use Python in your project, and are unsure about the possibilities because we are still in the middle of the section on Python, you can contact me to push back your due date for this proposal.

</div>

Some pointers:

-   Create a directory for your project and start a Git repository. This will be a repository for the project as a whole, not just for this proposal. <span style="color:coral"><i>[1]</i></span>

-   Write the proposal in Markdown and include it in your repository. Like we did with the graded assignments, when you're done, push your repository to GitHub and tag me (`@jelmerp`) in an "Issue" on GitHub (please make sure to tag me in the text body for the issue, it won't be parsed as a tag if you do this in the title of the issue). <span style="color:coral"><i>[1]</i></span>

-   In the proposal, start with a general description of what your project will be about, without going into detail about coding languages and approaches. Describe what data you will work with and what kind of output your project will produce. (This can be pretty minimal if your project is "code-first" with a trivial data set.) <span style="color:coral"><i>[2]</i></span>

-   Next, summarize how you envision the more technical aspects: in which language(s) do you intend to code, what do you think you will need separate scripts for, and how will you structure results? Will you mostly be coding your data processing/analyses from scratch, or are you primarily running external programs? <span style="color:coral"><i>[2]</i></span>

-   Check the list of graded aspects on the [page with general information about the project](final_project.html). If you are not sure you will be able to fulfill one of these, or intend to skip something (e.g. OSC SLURM jobs), mention that here.

-   Briefly mention which aspects of your project you are uncertain about, for instance because you intend to include some topics that we have yet to cover in the course, or because something will depend on how other things go. <span style="color:coral"><i>[2]</i></span>

-   Finally, briefly describe why you chose to pick this project. Because it will be useful for your research? Because it gives you practice with coding topics you like or that you want to / need to get better with? All of the above and/or something else? <span style="color:coral"><i>[2]</i></span>
