---
title: "Final project: presentations"
output:
  distill::distill_article:
    self_contained: false
---

**Every student is expected to give a 10-minute presentation about their final**
**project during the Zoom sessions on April 20th and 22nd.**
**<span style="color:coral"><i>[10 points]</i></span>**

<br>

**A few pointers:**

- Aim for the presentation itself to take about 10 minutes --
  the acceptable range is roughly 8-11 minutes.

- Afterwards, be prepared to answer a few questions both from your peers and the
  TA or instructor.
  You're also expected to ask one or more questions (in total) to other students
  after their presentations.
  
- Prepare at least several slides.
  Your entire presentation can be given using slides. But if you want,
  you can also switch to showing your actual repository / scripts during part
  of the presentation (just be mindful of font sizes if you do the latter).

- Start with some general background about the data / research project,
  and an overview of the goals of the project. 

- You can see for yourself if you would like to run through some code
  line-by-line, or give a more high-level overview of the code you've written.

- At the end, briefly mention what you still have to do --
  and if this is work that you will continue after this course,
  you can also discuss this in a broader sense.
  You can even explicitly ask for some advice, if you want.

**What you will be graded on:**

- Technical content  <span style="color:coral"><i>[3 points]</i></span>
- Contextualization <span style="color:coral"><i>[2 points]</i></span>
- Delivery <span style="color:coral"><i>[2 points]</i></span>
- Clarity <span style="color:coral"><i>[2 points]</i></span>
- Questions for other students <span style="color:coral"><i>[1 point]</i></span>
