---
title: "Glossary"
output:
  distill::distill_article:
    self_contained: false
---


KEY TERMS

 Buffalo	 Book: Bioinformatics Data Skills (Buffalo 2015)
 CSB	 Book: Computing Skills for Biologists (Allesina & Wilmes 2019)
 git	 Software for version control
 Github	 A website that hosts git projects, which are known as repositories
 Markdown	 A simple text markup language (think LaTeX or HTML but much simpler)
 OSC	 The Ohio Supercomputer Center
 Python	 A programming language
 shell	
 The Unix shell is a command-line interface to your operating system that runs within a terminal.
 - There are several shell flavors, and in this course, we will be working with the bash shell.

 Snakemake	 Software for automated workflow (pipeline) management
 SLURM	 The compute job scheduling system used at the Ohio Supercomputer Center
 Unix	 A family of operating systems that includes Mac and Linux, but not Windows
 
 ADDITIONAL TERMS
 
 CLI	 Command-line Interface -- a software interface with which one interacts by typing commands (cf. GUI)
 dir	 Directory, which is Unix-speak for a folder on your computer
 GUI	 Graphical User Interface -- a visual software interface with which one interacts by clicking
