---
title: "Further resources"
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 3
---

## Shell

### Books

The first two are available online at the OSU library:

- [The Linux Command Line: A Complete Introduction](https://library.ohio-state.edu/record=b8640501~S7)
  (William Shotts, 2019)

- [Linux Command Line and Shell Scripting Bible](https://library.ohio-state.edu/record=b9161748~S7)
  (Christine Bresnahan, 2015)

- [Command Line Kung Fu: Bash Scripting Tricks, Linux Shell Programming Tips, and Bash One-liners](https://www.amazon.com/dp/1499222033) (Jason Cannon, 2014) 

### Misc

- [Software Carpenty shell tutorial](http://swcarpentry.github.io/shell-novice/)
  For another angle on some of what we've also learned in this course.

### Useful oneliners, mostly for bioinformatics

- [By Stephen Turner](https://github.com/stephenturner/oneliners/blob/master/README.md)

- [By Tommy Ming](https://github.com/crazyhottommy/bioinformatics-one-liners)

### Background reading

- [Five reasons why researchers should learn to love the command line](https://www.nature.com/articles/d41586-021-00263-0)

<br>

## Project organization, reproducibility, and best practices

- [Good enough practicaes in scientific computing](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510)
(Wilson et al. 2017, PLoS Computational Biology)

- [The plain person's guide to plain text social science](https://plain-text.co/)
  (Kieran Healy)

- [Streamlining data-intensive biology with workflow systems](https://academic.oup.com/gigascience/article/10/1/giaa140/6092773)
  (Reiter et al. 2021, GigaScience)

<br>

## Git

### Books

I wouldn't necessarily recommend diving so deep into Git as to read a book about
it, but this book at the very least provides an excellent reference,
and is freely available online: [Pro Git](http://git-scm.com/book/en/v2).

### Online practice

- [Git-it](https://github.com/jlord/git-it-electron#git-it) -- a small application to learn and practice Git and GitHub basics.

- [Visualizing Git](http://git-school.github.io/visualizing-git/)  
  These visualizations can help to get some intuition for Git.
  Note that at the prompt, you can only type Git commands and since there are
  no actual files involved, you can't use `git add` -- just commit straight away. 

- [Learn Git branching](https://learngitbranching.js.org/)

- Quick [GitHub overview](https://guides.github.com/activities/hello-world/)  
  of some Git and GitHub functionality including branching
  and Pull Requests, and how to do these things in your browser at GitHub. 

### Misc

- [Excuse me, do you have a moment to talk about version control?](https://peerj.com/preprints/3159/) (Bryan 2017, PeerJ)

- [An overview of Git tutorials](https://gist.github.com/jaseemabid/1321592)

- [Happy Git and GitHub for the useR](https://happygitwithr.com/)  
  Somewhat R-centric, but a very accessible introduction to Git.

- [Git best practices by Seth Robertson] (https://sethrobertson.github.io/GitBestPractices/)

- [Atlassian Git tutorials](https://www.atlassian.com/git/tutorials/what-is-version-control)  
  Atlassian is behind Bitbucket, an alternative to GitHub that also hosts Git
  repositories, and its Git tutorials are very useful.

<br>

## Python

### Books

These are all available online, freely or via the OSU library:

- [Python for the life sciences: a gentle introduction to python for life scientists](https://library.ohio-state.edu/record=b8792177~S7)
  (Alexandar Lancestar, 2019).  
  Very explicitly geared towards biologists with no or little
  programming experience, and takes a very practical and project-oriented
  approach. From what I've seen of the book, I can highly recommended it! 

- [Python for Bioinformatics](https://library.ohio-state.edu/record=b8257944~S7)
  (Sebastian Bassi, 2018).  
  Starts with an introduction to Python and then has chapters that
  each describe practical problems/projects for Python.  
  ([Associated GitHub repository](https://github.com/serulab/py4bio).)
  
- [Python programming for biology, bioinformatics, and beyond](https://library.ohio-state.edu/record=b8928994~S7) (Tim Stevens, 2015).  
  Starts with an introduction to Python and then has chapters on topics
  like "Pairwise sequence alignments", "Sequence variation and evolution",
  and "High-throughput sequences".

- [Reproducible Bioinformatics with Python](https://library.ohio-state.edu/record=b9208582~S7) (Ken Youens-Clark, 2021).  
  A slightly more advanced book that does not start with an introduction
  to Python, but you should be able to follow the book with what you've learned
  in this course.
  
- [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/)
(Jake VanderPlas, 2016).  
  Focused on NumPy, Pandas, visualization with Matplotlib,
  and machine learning with scikit-learn. Freely available online.

- [Python for Data Analysis](https://library.ohio-state.edu/record=b9170181~S7)
  (Wes McKinney, 2017).  
  Focused on NumPy, Pandas, and visualization with Matplotlib.

- [Dive Into Python 3](https://diveintopython3.problemsolving.io/)
  Mark Pilgrim, 2009
  
### Courses

- [Python for everybody](https://www.py4e.com/) -- Includes course materials
  and lectures, and is also available at Coursera and edX.

- [Programming for Biology](http://programmingforbiology.org/index.html) --
  This is the Cold Spring Harbor course that your TA Zach took,
  and the materials are available online.

- [Using Python for Research](https://www.edx.org/course/using-python-for-research)
  Free edX course -- you can also find links to just the videos towards the
  bottom of [this page](http://rafalab.github.io/pages/harvardx.html).

- [Data analysis with Python at freeCodeCamp](https://www.freecodecamp.org/learn/data-analysis-with-python/)

- [Videos from the MIT course "Introduction to Computer Science and Programming in Python"](https://www.youtube.com/playlist?list=PLUl4u3cNGP63WbdFxL8giv4yhgdMGaZNA)

### Library-specific material

- [The official NumPy tutorial](https://numpy.org/doc/stable/user/absolute_beginners.html)

- [Pandas tutorials and documentation](https://pandas.pydata.org/docs/getting_started/intro_tutorials/)

- [Material for a BioPython workshop](https://github.com/peterjc/biopython_workshop/)

- [The BioPython Tutorial and Cookbook](http://biopython.org/DIST/docs/tutorial/Tutorial.html)

### Coding infrastructure

#### VS Code

- [VS Code documentation on its "Python Interactive Window"](https://code.visualstudio.com/docs/python/jupyter-support-py).

- [VS Code documentation on its Jupyter Notebook implementation](https://code.visualstudio.com/docs/python/jupyter-support).

#### Jupyter Notebooks / JupyterLab

You can also use the Jupyter Notebooks / JupyterLab as an Interactive App at OSC OnDemand.
If you're interested in using this, I would recommend trying **JupyterLab** which
can run Jupyter Notebooks but also regular Python scripts, a shell, and so forth.

- [6-minute video: How to use JupyterLab](https://www.youtube.com/watch?v=A5YyoCKxEOU).

- [This JupyterLab documentation](https://jupyterlab.readthedocs.io/en/2.2.x/user/interface.html)
  provides a nice introduction to JupyterLab features
  (the link goes to documentation for a version close to the one at OSC).

- For a general introduction to Jupyter Notebooks, see also
  [How to Use Jupyter Notebook in 2020: A Beginner’s Tutorial](https://www.dataquest.io/blog/jupyter-notebook-tutorial/).

### Miscellaneous

- [A YouTube playlist of Microsoft videos introducing Python](https://www.youtube.com/watch?list=PLlrxD0HtieHhS8VzuMCfQD4uJ9yne1mE6&v=jFCNu1-Xdsw)

#### Best practices

- [PEP 8 — the Style Guide for Python Code](https://pep8.org/)

- [Ten simple rules for writing and sharing computational analyses in Jupyter Notebooks ](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1007007)
  -- Rule et al. 2019, PLoS Computational Biology
  
#### Meta

- [Stack Overflow: "The Incredible Growth of Python" (2017)](https://stackoverflow.blog/2017/09/06/incredible-growth-python/)

- [Statista: "Python Remains Most Popular Programming Language" (2020)](https://www.statista.com/chart/21017/most-popular-programming-languages/)

- [The Economist: "Python is becoming the world’s most popular coding language" (2018)](https://www.economist.com/graphic-detail/2018/07/26/python-is-becoming-the-worlds-most-popular-coding-language)

<br>

## Snakemake

- [The official Snakemake tutorial](https://snakemake.readthedocs.io/en/stable/tutorial/tutorial.html).  
  Can be run in your browser!

- [A short Snakemake introduction by Vince Buffalo](https://vincebuffalo.com/blog/2020/03/04/understanding-snakemake.html)

- [A useful Snakemake tutorial by NBIS](https://nbis-reproducible-research.readthedocs.io/en/latest/snakemake/)

- A Carpentries lesson on working on a compute cluster,
  with a large section on Snakemake starting on
  [this page](http://www.hpc-carpentry.org/hpc-python/07-snakemake-intro/index.html).

### Background reading

- [Workflow systems turn raw data into scientific knowledge](https://www.nature.com/articles/d41586-019-02619-z)
  (Perkel 2019, Nature "Toolbox" feature).

- [Sustainable data analysis with Snakemake](https://zenodo.org/record/4240139)
  (Mölder et al. 2020, Zenodo).

<br>

## Miscellaneous

### Books along the lines of CSB

- [A Primer for Computational Biology](https://open.oregonstate.education/computationalbiology/)

- Practical Computing for Biologists

### Genomics and applied bioinformatics

- Two courses on genomic data analysis with lots of online material available:

  - [Applied Genomics course by Michael Schatz](https://github.com/schatzlab/appliedgenomics2020)

  - [Applied Computational Genomics course by Aaron Quinlan](https://github.com/quinlan-lab/applied-computational-genomics)

- Sites with online materials for lots of past computational biology workshops:

  - [UC Davis Bioinformatics Core](https://ucdavis-bioinformatics-training.github.io/)
  - [Harvard Chan Bioinformatics Core](https://hbctraining.github.io/Training-modules/)
  - [Bioinformatics.ca](https://bioinformaticsdotca.github.io/)
  - [Summer Institute in Statistical Genetics](https://si.biostat.washington.edu/suminst/archives/SISG2020)
  - [Genomics Curriculum of Data Carpentry](https://datacarpentry.org/lessons/#genomics-workshop)
  
- [Rosalind](http://rosalind.info/) -- A website with bioinformatics exercises
