---
title: "Week 2 -- Ungraded Assignment: <br> Create a GitHub account"
output:
  distill::distill_article:
    self_contained: false
---

### What?

Create a Github account and let me know you've done so.

### Why?

Github is a website that hosts *Git repositories*, i.e. version-controlled projects.
In Module 3 of this course, we will be learning how to use Git together with GitHub.
In addition, all graded assignments for this course will be submitted through Github.

### How?

*If you already have a GitHub account, [log in](https://github.com/) and start at step 6.*

1. Go to <https://github.com>.

2. Click "Sign Up" in the top right.

3. Fill out the form:
  
   - When choosing your **_username_**,
     I would recommend to
     *keep it professional and have it include or resemble your real name*.
     (This is because you will hopefully continue to use GitHub to share your code,
     for instance when publishing a paper.)
  
   - You can choose for yoursefl whether you want to use your OSU email address
     or a non-institutional **_email address_**.
     (And note that you can always associate a second email address with your account.)

   - You'll probably want to uncheck the box under "Email Preferences".

   - When you're done, click "Create account".
   
4. You can answer the questions that GitHub will now ask you,
   but you should also be able to just skip them.
   
5. Check your email and click the link to **_verify your email address_**.
   
6. In the far top-right of the page back on GitHub,
   click your randomly assigned avatar, and in the dropdown menu, click "Settings".

7. In the "Emails" tab (left-hand menu), deselect the box "Keep my email addresses private". 

8. In the "Profile" tab, enter your name.

9. Still in the "Profile tab", upload an avatar.
   This can be a picture of yourself but if you prefer, you can use something else.

