---
title: "Week 2: Content overview and readings"
output:
  distill::distill_article:
    self_contained: false
---

## Content overview for this week

This week, we'll talk about some best practices for project organization,
managing your project's files in the Unix shell,
and documenting your project with Markdown files.
We'll also spend a bit of time getting to know VS Code,
the text editor that you will spend a lot of time in during this course.

The reading for this week is Chapter 2 of the Buffalo book:
"Setting Up and Managing a Bioinformatics Project".

In an [ungraded assignment](../../w02_UA_github-signup.html)
to get set up for upcoming modules,
you will sign up for a Github account.
Like last week, there are [exercises](../../w02_exercises.html)
but no graded assignments (the first one will be issued next week).

**Some of the things you will learn this week:**

- Learn some best practices for project organization, documentation, and management.

- Learn how to apply these best practices this in the shell.

- Learn how to use Markdown for documentation (and beyond).

- Get to know our text editor for the course, VS Code, a bit better.

## Readings

This week's reading is Chapter 2 of our secondary book,
"Bioinformatics Data Skills" by Vince Buffalo
(the book will from now on be  referred to as "Buffalo"),
which deals with project organization and (file) management.

While very useful for any biologist interested in computational skills,
the Buffalo book is geared towards bioinformatics data, especially genomics data
in the Next-Generation Sequencing (NGS) era.
If you don't work with sequencing data,
don't fret about understanding the specifics of some of the examples and
recommendations, and hopefully, the more general underlying ideas will still be helpful.

The chapter also contains several tips and tricks for using the shell for
project organization,
which we will work through in the Zoom sessions.
For more material along these lines, optional reading is Buffalo Chapter 3. 

### Required readings

- [Buffalo](https://library.ohio-state.edu/record=b8538907~S7)
  Chapter 2: "Setting up and Managing a Bioinformatics Project"
  
### Optional readings

- [Buffalo](https://library.ohio-state.edu/record=b8538907~S7)
  Chapter 3: "Remedial Unix Shell"
  
### Further resources

- Wilson et al. 2017, PLOS Computational Biology:
  "[Good enough practices in scientific computing](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510)"

- Kieran Healy:
  ["The Plain Person’s Guide to Plain Text Social Science"](https://plain-text.co/)
