---
title: "Python resources"
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 3
---

## General resources for learning Python

Here is a list of recommended resources for learning Python.
Most are geared towards beginners (in Python and programming alike).
Also, the bioinformatics-specific books are all quite practical,
describing "applied bioinformatics" -- i.e. more how to analyze your data than
how to write your own algorithms.

### Available online via the OSU library

- Book: [Python for the life sciences: a gentle introduction to python for life scientists](https://library.ohio-state.edu/record=b8792177~S7)
  (Alexandar Lancestar, 2019).
  This book is very explicitly geared towards biologists with no or little
  programming experience, and takes a very practical and project-oriented
  approach. From what I've seen of the book, I can highly recommended it! 

- Book: [Python for Bioinformatics](https://library.ohio-state.edu/record=b8257944~S7)
  (Sebastian Bassi, 2018).
  This book also starts with an introduction to Python and then has chapters that
  each describe practical problems/projects for Python,
  like "Calculating melting temperature from a set of primers".  
  ([Associated GitHub repository](https://github.com/serulab/py4bio).)
  
- Book: [Python programming for biology, bioinformatics, and beyond](https://library.ohio-state.edu/record=b8928994~S7) (Tim Stevens, 2015).
  This book starts with an introduction to Python and then has chapters on topics
  like "Pairwise sequence alignments", "Sequence variation and evolution",
  and "High-throughput sequences".

- Book: [Reproducible Bioinformatics with Python](https://library.ohio-state.edu/record=b9208582~S7) (Ken Youens-Clark, 2021).
  This is a slightly more advanced book that does not start with an introduction
  to Python, but you should be able to follow the book with what you'll learn
  over the next couple of weeks in the course.

### Free online resources

#### Videos

- [A YouTube playlist of Microsoft videos introducing Python](https://www.youtube.com/watch?list=PLlrxD0HtieHhS8VzuMCfQD4uJ9yne1mE6&v=jFCNu1-Xdsw)

- [Videos from the MIT course "Introduction to Computer Science and Programming in Python"](https://www.youtube.com/playlist?list=PLUl4u3cNGP63WbdFxL8giv4yhgdMGaZNA)

#### Courses

- [Python for everybody](https://www.py4e.com/) -- Includes course materials
  and lectures, and is also available at Coursera and edX.

- [Programming for Biology](http://programmingforbiology.org/index.html) --
  This is the Cold Spring Harbor course that your TA Zach took,
  and the materials are available online.
  
### Not free
  
- Book: [Bioinformatics with Python Cookbook](https://www.amazon.com/Bioinformatics-Python-Cookbook-bioinformatics-computational/dp/1789344697) (Tiago Antao, 2018).

<br>

## Other resources

### Best practices

- [PEP 8 — the Style Guide for Python Code](https://pep8.org/)

- [Ten simple rules for writing and sharing computational analyses in Jupyter Notebooks ](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1007007) -- Rule et al. 2019, PLoS Computational Biology
  
### Miscellaneous

- [Stack Overflow: "The Incredible Growth of Python" (2017)](https://stackoverflow.blog/2017/09/06/incredible-growth-python/)

- [Statista: "Python Remains Most Popular Programming Language" (2020)](https://www.statista.com/chart/21017/most-popular-programming-languages/)

- [The Economist: "Python is becoming the world’s most popular coding language" (2018)](https://www.economist.com/graphic-detail/2018/07/26/python-is-becoming-the-worlds-most-popular-coding-language)

## Coding infrastructure

### VS Code

- [VS Code documentation on its "Python Interactive Window"](https://code.visualstudio.com/docs/python/jupyter-support-py).

- [VS Code documentation on its Jupyter Notebook implementation](https://code.visualstudio.com/docs/python/jupyter-support).

### Jupyter Notebooks / JupyterLab

You can also use the Jupyter Notebooks / JupyterLab as an Interactive App at OSC OnDemand.
If you're interested in using this, I would recommend trying JupyterLab which
can run Jupyter Notebooks but also regular Python scripts, a shell, and so forth.

::: {.content-box-info}

To do so at [OSC OnDemand](https://ondemand.osc.edu),
click on `Interactive Apps` (top blue bar) and then
`Jupyter (Owens and Pitzer)` near the bottom, and
check the box `Use JupyterLab instead of Jupyter Notebook?`.

:::

- [6-minute video: How to use JupyterLab](https://www.youtube.com/watch?v=A5YyoCKxEOU).

- [This JupyterLab documentation](https://jupyterlab.readthedocs.io/en/2.2.x/user/interface.html)
  provides a nice introduction to JupyterLab features
  (the link goes to documentation for a version close to the one at OSC).

- For a general introduction to Jupyter Notebooks, see also
  [How to Use Jupyter Notebook in 2020: A Beginner’s Tutorial](https://www.dataquest.io/blog/jupyter-notebook-tutorial/).
