---
title: "Week 9 - Control flow and working with files - II"
output:
  xaringan::moon_reader:
    seal: false
    css: ["default", "default-fonts", "slides.css", "slides_copy.css"]
    lib_dir: libs
    nature:
      highlightStyle: rainbow
      highlightLines: true
      countIncrementalSlides: false
---
class:inverse middle center

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)

knitr::opts_chunk$set(eval = FALSE)
```

# *Week 9 - Control flow and working with files*

----

# II: Working with files

<br> <br> <br> <br> <br>

### Jelmer Poelstra
### 2021/03/02 (updated: `r Sys.Date()`)

---
class: inverse middle center

# Overview

----

.left[
- ### [JupyterLab tips and tricks](#juplab)
- ### [Working with files](#files)
]

---

## More JupyterLab

- Viewing two notebooks side-by-side & `View` => `Single Document Mode`.

- You can modify keyboard shortcuts via `Settings` => `Advanced Settings Editor`
  => `Keyboard Shortcuts`.

- JupyterLab also has a text editor, so you can open and edit any kind of text
  file. Moreover, you can get HTML previews for Markdown files
  (and this can go side-by-side with the source.)

- New launcher (`+`) => `Show Contextual Help` => drag next to Notebook =>
  will show help for whatever object / function you have selected.

- Upload and download files.

- Closing a Notebook doesn't stop it from running.
  To stop it, go to the `Running` panel in the sidebar, and click `SHUTDOWN`
  for the notebook in question.

- Console for other types of files, e.g. Markdown and `.py` scripts.

---

## More Jupyter tricks

- Magic functions

- `!ls`

- `%%bash` for a bash cell

- <kbd>Shift</kbd>+<kbd>Enter</kbd> &ndash; Run a cell and move to the next one.
- <kbd>Ctrl</kbd>+<kbd>Enter</kbd> &ndash; Run a cell and stay in the current cell.
- <kbd>Alt</kbd>+<kbd>Enter</kbd> &ndash; Run a cell and insert a cell below
  (can be handy if there's already a cell below it.)


---

## `r icon::fa("user-edit")` Intermezzo 3.4

---

## `r icon::fa("user-edit")` Intermezzo 3.4: solutions

```sh
import csv

with open ("../data/Dalziel2016_data.csv") as f:
  reader = csv.DictReader(f)
  for row in reader:
    print(row["loc"], row["pop"])
```
