---
title: "Week 9 - Control flow and working with files - II"
output:
  xaringan::moon_reader:
    seal: false
    css: ["default", "default-fonts", "slides.css", "slides_copy.css"]
    lib_dir: libs
    nature:
      highlightStyle: rainbow
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)

knitr::opts_chunk$set(eval = FALSE)
```

## `r icon::fa("user-edit")` Intermezzo 3.3

---

## `r icon::fa("user-edit")` Intermezzo 3.3: solutions

1. `range(3, 17)` yields the numbers from 3 to 16, thus hello will be
   printed 14 times.

2. `range(12)` returns the numbers from 0 to 11.
   For each number whose remainder is 0 when divided by 3
   (i.e., the four numbers 0, 3, 6, and 9), `hello` is printed.

3. `range(15)` returns the numbers from 0 to 14.
   For each number whose remainder is 3 when divided by 5 or 4,
   hello is printed (i.e., `hello` is printed for j = 0, 7, 8, 11, 13).

4. For each cycle of the loop, we add `3` to `z` (starting with `z = 0`).
   Then `hello` is printed 5 times before `z != 15` becomes `False`
   (i.e., before `z == 15`).

5. The loop starts with `z` set to 12.
   In each cycle, we test whether `z` is smaller than `100` and evaluate whether
   `z` equals `31`.
   If this latter condition is met, `hello` is printed 7 times.
   In each cycle, we also test whether `z` equals `18.`
   If the condition evaluates to `True`, `hello` is printed (once).
   
   As such, hello is printed 8 times in total.

---

## `r icon::fa("user-edit")` Intermezzo 3.3: solutions

6. `range(10)` returns the numbers from 0 to 9.
   In each cycle, we test whether `i` is greater than `5`.
   As long as the if statement is `False` (i.e., i has values 0 to 5),
   we print hello — 6 times in total.
   When the if condition is `True` (i.e., when z takes the value 6),
   we encounter a break statement that terminates the loop.

7. As long as z is smaller than 25, we add 1 to z at every cycle.
   When the if condition is met (i.e., z is odd), the `continue` statement is
   executed and skips the remainder of the cycle,
   so the print statement is not executed.
  
  Only when the if statement is not `True` (i.e., `z` is even) is `hello` printed.
  There are 12 even numbers between 1 and 25.
