
---
class: center middle inverse

# BioPython (CSB 6.4)

-----

# I: Retrieving sequences from NCBI (6.4.1)

<br> <br> <br> <br>

---

## Using BioPython to inferface with NCBI databases

While we already downloaded some data from NCBI manually in the exercises for
week 7 (Bioinformatics Data),
we can also use NCBI's **"Entrez Programming Utilities"** to do this
programmatically.

BioPython includes an Entrez module that interfaces with NCBI Entrez. 
This is a much better method to find and download data, if you regularly need
to do so.

- We start by importing the module:
  
  ```python
  from Bio import Entrez
  ```

- As another setup step,
  we should provide our e-mail address to let NCBI know who we are:

  ```python
  Entrez.email = "me.1@osu.edu"  # Replace by your email address
  ```

---

## Search the database

- Create a "handle" to search results:

  ```python
  handle = Entrez.esearch(db = "nuccore",
                          term = ("Uropsilus investigator[Organism]"),
                          RetMax = 200)
  ```

- Read the results and close the handle:

  ```python
  search_results = Entrez.read(handle)
  handle.close()
  ```

<br>

- Our results are returned in the form of a dictionary,
  so let's look at the keys:
  
  ```python
  search_results.keys()
  #> dict_keys(['Count', 'RetMax', 'RetStart', 'IdList',
  #>            'TranslationSet', 'TranslationStack',
  #>             'QueryTranslation'])
  ```
  
---

## Looking at the results

- How many sequences did we find?  
  
  ```python
  search_results["Count"]
  '126'   # Has increased from '71' in the book!
  ```
  
- What is the list of GenBank identifiers?

  ```python
  id_list = search_results["IdList"]
  print(id_list)
  #> ['524853022', '555947199', '555947198', ... , '555946814']
  ```

- Did we get all 126 IDs in the list? Note that the default is to only return
  20, but because we used `RetMax = 200` in the call to `Entrez.esearch()`,
  we got all of them:

  ```python
  len(id_list)
  #> '126'
  search_results["RetMax"]
  #> '200'
  ```

---

## Downloading the sequences

We'll now use the GenBank IDs to actually download some sequences:

```python
search_handle = Entrez.efetch(db = "nuccore",
                              rettype = "fasta",
                              retmode = "text",
                              id = id_list)

# Set up a handle to an output file:
out_handle = open("Uropsilus_seq.fasta", "w")

# Write the obtained sequence data to the output file:
for line in handle:
    out_handle.write(line)

# Close the handles:
out_handle.close()
search_handle.close()
```

Next, we'll read in our FASTA file using SeqIO.

---

class: center middle inverse

# BioPython (CSB 6.4)

-----

# II: Input and output of sequence data using *SeqIO* (6.4.2)

<br> <br> <br> <br>

---

## Reading a FASTA file with SeqIO

- We start by importing the SeqIO module:

  ```python
  from Bio import SeqIO
  ```

- Let's print the ID and sequence length for each sequence:

  ```python
  in_handle = open("Uropsilus_seq.fasta", "r")
  
  for record in SeqIO.parse(in_handle, "fasta"):
      print(record.description)
      print(len(record), '\n')
  in_handle.close()
  
  #> KC516837.1 Uropsilus investigator isolate A11 apolipoprotein B (ApoB) gene, partial cds
  #> 573 
  
  #> KC516819.1 Uropsilus investigator voucher mlxs331 cytochrome c oxidase subunit I (COI) gene, partial cds, alternatively spliced; mitochondrial
  #> 912 
  
  #> KC516818.1 Uropsilus investigator voucher mlxs022 cytochrome c oxidase subunit I (COI) gene, partial cds, alternatively spliced; mitochondrial
  #> 912 
  #> [...]
  ```

---

## Selecting only sequences for the BMI1 genes

```python
# We will import the "re" module for regular expression searches:
import re

output_handle = open("Uropsilus_BMI1.fasta", "w")

for record in SeqIO.parse("Uropsilus_seq.fasta", "fasta"):
    
    # Find the BMI1 sequences using "re.search"
    if re.search("BMI1", record.description):
        print(record.id)
        short_seq = record[:100]  # Just take the first 100 bases
        SeqIO.write(short_seq, output_handle, "fasta")
        
output_handle.close()
```

---

class: center middle inverse

# BioPython (CSB 6.4)

-----

# III: Programmatic BLAST Search (6.4.3)

<br> <br> <br> <br>

---

## BLAST

The **Basic Local Alignment Search Tool (BLAST)** finds regions of similarity
between biological sequences,
and is one of the most widely used bioinformatics tool.

You may not it from its web interface, where you can paste in or upload some
sequences, and then "BLAST them" against a database you can specify.

### screenshot?


<br>

Using this web interface may be convenient when you have one or a few sequences,
but it is not very reproducible and completely unsuitable for automation.

---

## Getting set up for BLAST

Biopython provides the module `Bio.Blast` which we can use to run a BLAST search
against the NCBI's online databases.

We will import just a few of its functions: `NCBIWWW` for access to NCBI's
BLAST server (the BLAST analysis is still being performed there!),
and `NCBIXML` to parse the XML format that our results will be in

```python
# from Bio import SeqIO   # Should already be loaded
# from Bio import Entrez  # Should already be loaded
from Bio.Blast import NCBIWWW, NCBIXML
```

<br>

--

We will start by parsing our FASTA file with SeqIO,
and then converting the records into a list:

```python
handle = open("Uropsilus_BMI1.fasta", "r")
records = list(SeqIO.parse(handle, "fasta"))
```

---

## Our sequence records as a named list

What does this list that we created look like? Let's print the first 2 items:

```python
records[0:2]
#> [SeqRecord(seq=Seq('TATTATGCTGTTTTGTGAACCTGTAGAAAACAAGTGCTTTTTATCTTGAAATTC...CCA', SingleLetterAlphabet()), id='KF778086.1', name='KF778086.1', description="KF778086.1 Uropsilus investigator voucher KIZ:020539 polycomb ring finger oncoprotein (BMI1) gene, 3' UTR", dbxrefs=[]),
#> SeqRecord(seq=Seq('TATTATGCTGTTTTGTGAACCTGTAGAAAACAAGTGCTTTTTATCTTGAAATTC...CCA', SingleLetterAlphabet()), id='KF778085.1', name='KF778085.1', description="KF778085.1 Uropsilus investigator voucher KIZ:020527 polycomb ring finger oncoprotein (BMI1) gene, 3' UTR", dbxrefs=[])]
```

### More about this list type

Say that the fourth sequence is the one we are interested in:

```python
print(records[3].id, " ", records[3].seq)
#> KF778083.1   TATTATGCTGTTTTGTGAACCTGTAGAAAACAAGTGCTTTTTATCTTGAAATTCAACAAATGGAAAGAATATGCATAGAATAATGCATTCTATGTAGCCA
```

---

## Run the BLAST search

For our BLAST search, we will use the nucleotide database (`nt`)
with the `blastn` algorithm, one of several BLAST variants
(other options are `blastp`, `blastx`, `tblastn`, and `tblastx`).

The `qblast()` function requires three arguments: the program (`blastn` for us),
the database (`nt` for us), and the query sequence (our 4th record from the
FASTA file): 

```python
Entrez.email = "me.999@osu.edu"

result_handle = NCBIWWW.qblast("blastn", "nt", records[3].seq)
```

Now, we will write our results, which are in XML format, to an XML file
and then close the result handle:

```python
save_file = open("my_blast.xml", "w")
save_file.write(result_handle.read())
save_file.close()

result_handle.close()
```

---

## Parse the XML file

We will now parse our XML file with blast results using the `NCBIXML` parser:

```python
result_handle = open("my_blast.xml")
blast_records = NCBIXML.read(result_handle)
```

(Because we our query consisted only of a single sequence,
we could use `NCBIXML.read()`.
For multiple sequences, you should use `NCBIXML.parse`.)

---

## Processing the BLAST results

Next, we loop through the individual alignment hits and then for each hit
through the "High-Scoring Pairs" (HSPs, subsequences with a good match).

For each High-Scoring Pair, we check whether the match is good enough
according to an arbitrary E-value (`E_VALUE_THRESH`) and length (`LEN_THRESH`)
that we set.

```python
E_VALUE_THRESH = 0.04
LEN_THRESH = 3000

for alignment in blast_records.alignments:
    
    for hsp in alignment.hsps:
        
        if hsp.expect < E_VALUE_THRESH and alignment.length > LEN_THRESH:
            
            print("****Alignment****")
            print("sequence:", alignment.title)
            print("length:", alignment.length)
            print("E value:", hsp.expect)
            print(hsp.query[0:75] + "...")
            print(hsp.match[0:75] + "...")
            print(hsp.sbjct[0:75] + "...")
```

---

## Processing the BLAST results

```python
E_VALUE_THRESH = 0.04
LEN_THRESH = 3000

for alignment in blast_records.alignments:
    
    for hsp in alignment.hsps:
        
        if hsp.expect < E_VALUE_THRESH and alignment.length > LEN_THRESH:
            
            print("****Alignment****")
            print("sequence:", alignment.title)
            print("length:", alignment.length)
            print("E value:", hsp.expect)
            print(hsp.query[0:75] + "...")
            print(hsp.match[0:75] + "...")
            print(hsp.sbjct[0:75] + "...")
#> ****Alignment****
#> sequence: gi|1304911126|ref|XM_006933246.4| PREDICTED: Felis catus BMI1 proto-oncogene, polycomb ring finger (BMI1), transcript variant X3, mRNA
#> length: 3523
#> E value: 2.25861e-42
#> TATTATGCTGTTTTGTGAACCTGTAGAAAACAAGTGCTTTTTATC...
#> |||||||||||||||||||||||||||||||||||||||||||||...
#> TATTATGCTGTTTTGTGAACCTGTAGAAAACAAGTGCTTTTTATC...
#> [...]
```

---
class: center middle inverse

# Questions?

-----

<br> <br> <br> <br>


---
class: center middle inverse

# Bonus material

-----

<br> <br> <br> <br>

---

class: center middle inverse

# BioPython (CSB 6.4)

-----

# IV: Querying PubMed for scientific literature information (6.4.4)

<br> <br> <br> <br>

---
background-color: #f2f5eb

## PubMed search

